// 设置类型数据
export const SET_TYPE = 'SET_TYPE'
export const PRODUCT_TYPE_LIST_SET = 'PRODUCT_TYPE_LIST_SET'
export const PRODUCT_KEYWORDS_LIST_SET = 'PRODUCT_KEYWORDS_LIST_SET'
export const PERMISSION_LIST_SET = 'PERMISSION_LIST_SET'
